# Generated by Django 3.2.15 on 2022-08-19 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_user_options'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeToBenefactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefactr_to_exchnage', to='users.beneficiary')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_to_benefactor', to='exchanges.exchanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exchange_to_benefactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
