# Generated by Django 3.2.15 on 2022-08-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220820_2059'),
        ('exchanges', '0002_exchangetobenefactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='logo',
            field=models.ImageField(default='images/logo-primary', upload_to='images/exchanges'),
        ),
        migrations.AlterField(
            model_name='exchangetobenefactor',
            name='benefactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefactor_to_exchnage', to='users.beneficiary'),
        ),
    ]
