# Generated by Django 3.2.15 on 2022-08-14 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('identifier', models.TextField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_exchange', to='exchanges.exchanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flowers', to=settings.AUTH_USER_MODEL, verbose_name='Owner of this API')),
            ],
        ),
    ]
