# Generated by Django 3.2.15 on 2022-08-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
        ('flowers', '0005_alter_flowers_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='identifier',
            field=models.ForeignKey(limit_choices_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flowers', to=settings.AUTH_USER_MODEL, verbose_name='Owner of this API'), on_delete=django.db.models.deletion.CASCADE, related_query_name='user_beneficiary', to='users.beneficiary'),
        ),
    ]
