# Generated by Django 3.2.15 on 2022-08-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_flowers_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='identifier',
        ),
    ]
