# Generated by Django 3.2.15 on 2022-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='coin_ticker',
            field=models.CharField(default='USDT', help_text='The coin ticker e.g USDT, BNB, ETH, etc.', max_length=6),
        ),
    ]
