# Generated by Django 3.2.15 on 2022-08-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_beneficiary_coin_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_flowers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_willed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_firsttime',
            field=models.BooleanField(default=True),
        ),
    ]
